package org.example.ordermanagement.exception.dto;

public enum Code {
    ORDER_NOT_FOUND,
    PRODUCTS_NOT_FOUND,
    NULL_CASHIER_ID,
    CREATION_ORDER_NULL,
    CUSTOMER_NOT_FOUND,
    ORDER_NOT_FOUND_FOR_THIS_ORDER_ITEM,
    PRODUCT_NOT_FOUND_FOR_THIS_ORDER_ITEM,
    PRICE_NOT_FOUND_FOR_THIS_ORDER_ITEM,
    ORDER_ITEM_ADDITION_NULL,
    ORDER_FINALIZATION_NULL,
    //Customer
    CUSTOMER_REQUEST_NULL,
    PRICE_REQUEST_NULL,


}
