package org.example.ordermanagement.controller.dto.order;


import lombok.*;
import org.example.ordermanagement.controller.dto.customer.CustomerDto;
import org.example.ordermanagement.controller.dto.orderitem.OrderItemDto;
import org.example.ordermanagement.model.Customer;
import org.example.ordermanagement.model.Status;

import java.time.LocalDateTime;
import java.util.List;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
public class OrderDto {

    private Long id;

    private LocalDateTime createdAt;

    private int cashierId;

    private int amountPaid;

    private Status status;

    private CustomerDto customerDto;
    private List<OrderItemDto> orderItemDtos;
    private int totalPrice;

}

// Communication between microservices.
// 1. Rest API, Web Client or Rest Client, Rest template (don't use it).
// 2. Analytics:
// 2.1.Number of customers, grouped by city
// 2.2.Find the first 5 selling products, grouped by city
// 2.3.Find the revenue generated by each city
// 2.4.
// 3. Research about security, Authentication, Authorization, JWT, Cookies.
